---
services:
  cache:
    image: valkey/valkey:alpine3.22
    restart: always
    ports:
      - "6379:6379"
    env_file:
      - .env
    command: valkey-server --save 20 1 --loglevel warning --requirepass "${REDIS_PASSWORD}"
    volumes:
      - ./valkey-data:/root/valkey
      - /etc/valkey/valkey.conf:/usr/local/etc/valkey/valkey.conf
